### ISSUE TITLE
URL Problem

### ISSUE THREAD

**Issue by saman** [mamal72/open-in-code#1]
Thanks for the useful extension. 
Did you change the address of this item (when the extension is disabled)? because it goes to [here](https://github.com/mamal72/open-in-vscode)!

<img width="237" alt="screen shot 2017-05-28 at 01 12 14" src="https://cloud.githubusercontent.com/assets/1576246/26524850/02679e92-4343-11e7-858b-940864fb58d1.png">

**Comment by mamal72** [comment]
Thanks for opening this issue. I decided to don't use VS in the name of the extension to prevent legal problems with MS as the VS is a registered trademark of MS. It's why the name changed to `open-in-code`. I forgot to update URL in the manifest file. Updating now.

Thanks for informing me. 🙏
